### ISSUE TITLE
minPoliciesToCheck to 1

### ISSUE THREAD

**Issue by zeroknots** [erc7579/smartsessions#37]

**Comment by zeroknots** [comment]
user op can be 0
action to be min 1

**Comment by filmakarov** [comment]
There can be the case, when user wants to configure sudo permission
Then user has to enable sudo policy as userOp policy (because it should work for all action ids)
then there will be no action policies, however the minimum is one currently
minPolicies: 1 // minimum of one actionPolicy must be set.
so we should probably make userOpPolicies+actionPolicies >= 1

**Comment by filmakarov** [comment]
See PR #85
